language: php

php:
  - 5.6
  - 7.0

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --no-dev --verbose"

script:
<<<<<<< HEAD
  - "phpunit -c phpunit.xml.dist"
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="7b45efc26f53d18ff308712f458eea708586c64c1ec162c101b6dff2079770bf" --format=php-clover build/logs/clover.xml

=======
  - "phpunit -c phpunit.xml.dist"
>>>>>>> upstream/master
